# Generated by Django 4.2.7 on 2025-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about_text',
            field=models.TextField(blank=True),
        ),
    ]
